:broom: Remove jest error monkey patch, now that we are no longer using jest.
Compilation error in /home/caleb/work/travel-authorization/api/src/db/db-client.ts
[ERROR] 18:01:40 ⨯ Unable to compile TypeScript:
src/db/db-client.ts(5,10): error TS2305: Module '"@/db/utils/monkey-patch-sequelize-errors-for-jest"' has no exported member 'monkeyPatchSequelizeErrorsForJest'.