:loud_sound: Add better logging around jwt middleware.
Why? Do I don't have to wonder where
> error: getaddrinfo EAI_AGAIN dev-0tc6bn14.eu.auth0.com {"code":"EAI_AGAIN","errno":-3001,"hostname":"dev-0tc6bn14.eu.auth0.com","syscall":"getaddrinfo"}
is comming from any more.

Turns out my vpn can cause auth0 not to be found EAI_AGAIN is a DNS failure.